name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish to PyPI

    permissions:
       id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install pdm

      - name: Build for PyPI
        run: |
          pdm build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
